version: 3.3.0.{build}
os: Visual Studio 2015
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
  - ps: .\scripts\show-dotnet-info.ps1
  - ps: .\scripts\set-version.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release test\NUnit.Portable.Agent.Tests\
  - cmd: dotnet run -c Release -p test\NUnit.Portable.Agent.Tests\
  - cmd: dotnet pack -c Release src\NUnit.Portable.Agent\

test: off

artifacts:
  path: 'src\NUnit.Portable.Agent\bin\Release\*.nupkg'
